CREATE TYPE "public"."act_kind" AS ENUM('approval', 'denial_list', 'name_change', 'revocation', 'loss_of_nationality', 'other');--> statement-breakpoint
CREATE TYPE "public"."age_bucket" AS ENUM('0-17', '18-24', '25-34', '35-44', '45-54', '55-64', '65+');--> statement-breakpoint
CREATE TYPE "public"."appeal_link_method" AS ENUM('process', 'name', 'none');--> statement-breakpoint
CREATE TYPE "public"."day_coverage" AS ENUM('covered', 'missing', 'no_edition');--> statement-breakpoint
CREATE TYPE "public"."decision_kind" AS ENUM('denial', 'approval', 'void', 'other');--> statement-breakpoint
CREATE TYPE "public"."fetch_status" AS ENUM('pending', 'fetched', 'gone', 'failed');--> statement-breakpoint
CREATE TYPE "public"."ingest_origin" AS ENUM('backfill', 'incremental');--> statement-breakpoint
CREATE TYPE "public"."ingest_status" AS ENUM('pending', 'running', 'enumerated', 'no_edition', 'failed');--> statement-breakpoint
CREATE TYPE "public"."job_status" AS ENUM('running', 'success', 'failed');--> statement-breakpoint
CREATE TYPE "public"."naturalization_type" AS ENUM('ordinaria', 'extraordinaria', 'provisoria', 'other');--> statement-breakpoint
CREATE TYPE "public"."parse_status" AS ENUM('pending', 'ok', 'partial', 'schema_mismatch', 'failed');--> statement-breakpoint
CREATE TYPE "public"."reason_source" AS ENUM('rule', 'legal_ref', 'similarity', 'llm', 'manual');--> statement-breakpoint
CREATE TYPE "public"."reason_status" AS ENUM('draft', 'active', 'merged');--> statement-breakpoint
CREATE TYPE "public"."review_state" AS ENUM('auto', 'needs_review', 'confirmed', 'corrected');--> statement-breakpoint
CREATE TYPE "public"."selected_by" AS ENUM('hierarchy', 'keyword', 'both');--> statement-breakpoint
CREATE TYPE "public"."subject_kind" AS ENUM('naturalization', 'expulsion', 'nationality_loss', 'other');--> statement-breakpoint
CREATE TABLE "acts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"page_id" uuid NOT NULL,
	"edition_date" date NOT NULL,
	"ordinal" integer NOT NULL,
	"identifica_raw" text,
	"act_kind" "act_kind" DEFAULT 'other' NOT NULL,
	"naturalization_type" "naturalization_type",
	"legal_basis" text[],
	"paragraphs" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"body_sha256" text,
	"parse_notes" text
);
--> statement-breakpoint
CREATE TABLE "approvals" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"act_id" uuid NOT NULL,
	"page_id" uuid NOT NULL,
	"edition_date" date NOT NULL,
	"ordinal" integer NOT NULL,
	"full_name" text NOT NULL,
	"name_norm" text NOT NULL,
	"foreign_id" text,
	"country_raw" text,
	"country_id" smallint,
	"birth_date" date,
	"birth_date_raw" text,
	"age_at_publication" smallint,
	"parents_raw" text,
	"state_raw" text,
	"state_id" smallint,
	"process_number" text,
	"process_number_norm" text,
	"paragraph_text" text NOT NULL,
	"paragraph_sha256" text NOT NULL,
	"parse_confidence" numeric(3, 2),
	"parser_version" integer DEFAULT 1 NOT NULL,
	"retired_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "br_state_aliases" (
	"alias_norm" text PRIMARY KEY NOT NULL,
	"state_id" smallint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "br_states" (
	"id" smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "br_states_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START WITH 1 CACHE 1),
	"uf" text NOT NULL,
	"name_pt" text NOT NULL,
	"name_en" text NOT NULL,
	"name_ru" text NOT NULL,
	"region" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "countries" (
	"id" smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "countries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START WITH 1 CACHE 1),
	"iso2" text NOT NULL,
	"iso3" text,
	"name_pt" text NOT NULL,
	"name_en" text NOT NULL,
	"name_ru" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "country_aliases" (
	"alias_norm" text PRIMARY KEY NOT NULL,
	"country_id" smallint NOT NULL,
	"is_ambiguous" boolean DEFAULT false NOT NULL,
	"note" text
);
--> statement-breakpoint
CREATE TABLE "daily_age_bucket_stats" (
	"day" date NOT NULL,
	"bucket" "age_bucket" NOT NULL,
	"approvals" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "daily_age_bucket_stats_day_bucket_pk" PRIMARY KEY("day","bucket")
);
--> statement-breakpoint
CREATE TABLE "daily_country_stats" (
	"day" date NOT NULL,
	"country_id" smallint NOT NULL,
	"approvals" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "daily_country_stats_day_country_id_pk" PRIMARY KEY("day","country_id")
);
--> statement-breakpoint
CREATE TABLE "daily_reason_category_stats" (
	"day" date NOT NULL,
	"category_id" smallint NOT NULL,
	"denials" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "daily_reason_category_stats_day_category_id_pk" PRIMARY KEY("day","category_id")
);
--> statement-breakpoint
CREATE TABLE "daily_state_stats" (
	"day" date NOT NULL,
	"state_id" smallint NOT NULL,
	"approvals" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "daily_state_stats_day_state_id_pk" PRIMARY KEY("day","state_id")
);
--> statement-breakpoint
CREATE TABLE "daily_stats" (
	"day" date PRIMARY KEY NOT NULL,
	"approvals" integer DEFAULT 0 NOT NULL,
	"denials_new" integer DEFAULT 0 NOT NULL,
	"denials_upheld" integer DEFAULT 0 NOT NULL,
	"other_decisions" integer DEFAULT 0 NOT NULL,
	"pages" integer DEFAULT 0 NOT NULL,
	"acts" integer DEFAULT 0 NOT NULL,
	"coverage" "day_coverage" DEFAULT 'covered' NOT NULL,
	"computed_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "denial_reasons" (
	"denial_id" uuid NOT NULL,
	"reason_id" uuid NOT NULL,
	"category_id" smallint NOT NULL,
	"edition_date" date NOT NULL,
	CONSTRAINT "denial_reasons_denial_id_reason_id_pk" PRIMARY KEY("denial_id","reason_id")
);
--> statement-breakpoint
CREATE TABLE "denials" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"act_id" uuid NOT NULL,
	"page_id" uuid NOT NULL,
	"edition_date" date NOT NULL,
	"block_ordinal" integer NOT NULL,
	"codigo" text,
	"assunto_raw" text,
	"decision_kind" "decision_kind" DEFAULT 'denial' NOT NULL,
	"is_upheld" boolean DEFAULT false NOT NULL,
	"subject_kind" "subject_kind" DEFAULT 'naturalization' NOT NULL,
	"is_republication" boolean DEFAULT false NOT NULL,
	"counts_as_new_denial" boolean DEFAULT true NOT NULL,
	"process_number" text,
	"process_number_norm" text,
	"full_name" text NOT NULL,
	"name_norm" text NOT NULL,
	"reason_text_id" uuid,
	"appeal_of_id" uuid,
	"appeal_link_method" "appeal_link_method" DEFAULT 'none' NOT NULL,
	"parser_version" integer DEFAULT 1 NOT NULL,
	"retired_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "dirty_days" (
	"day" date PRIMARY KEY NOT NULL,
	"reason" text NOT NULL,
	"marked_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ingest_day_snapshots" (
	"edition_date" date NOT NULL,
	"section" text DEFAULT 'do1' NOT NULL,
	"json_raw" text NOT NULL,
	"sha256" text NOT NULL,
	"fetched_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ingest_day_snapshots_edition_date_section_pk" PRIMARY KEY("edition_date","section")
);
--> statement-breakpoint
CREATE TABLE "ingest_days" (
	"edition_date" date NOT NULL,
	"section" text DEFAULT 'do1' NOT NULL,
	"status" "ingest_status" DEFAULT 'pending' NOT NULL,
	"origin" "ingest_origin" DEFAULT 'incremental' NOT NULL,
	"priority" smallint DEFAULT 0 NOT NULL,
	"articles_found" integer,
	"relevant_found" integer,
	"attempts" integer DEFAULT 0 NOT NULL,
	"next_attempt_at" timestamp with time zone,
	"last_error" text,
	"started_at" timestamp with time zone,
	"completed_at" timestamp with time zone,
	CONSTRAINT "ingest_days_edition_date_section_pk" PRIMARY KEY("edition_date","section")
);
--> statement-breakpoint
CREATE TABLE "job_runs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"job_name" text NOT NULL,
	"queue_job_id" text,
	"attempt" integer DEFAULT 1 NOT NULL,
	"status" "job_status" DEFAULT 'running' NOT NULL,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"finished_at" timestamp with time zone,
	"duration_ms" integer,
	"items_processed" integer DEFAULT 0 NOT NULL,
	"error" text,
	"meta" jsonb
);
--> statement-breakpoint
CREATE TABLE "llm_cache" (
	"prompt_version" text NOT NULL,
	"input_sha256" text NOT NULL,
	"response" jsonb NOT NULL,
	"model" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "llm_cache_prompt_version_input_sha256_pk" PRIMARY KEY("prompt_version","input_sha256")
);
--> statement-breakpoint
CREATE TABLE "reason_categories" (
	"id" smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reason_categories_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START WITH 1 CACHE 1),
	"code" text NOT NULL,
	"name_ru" text NOT NULL,
	"name_en" text NOT NULL,
	"color_slot" smallint NOT NULL,
	"sort_order" smallint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "reason_text_reasons" (
	"reason_text_id" uuid NOT NULL,
	"reason_id" uuid NOT NULL,
	"method" "reason_source" NOT NULL,
	"rule_code" text,
	"confidence" numeric(4, 3),
	"span_start" integer,
	"span_end" integer,
	"rules_version" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "reason_text_reasons_reason_text_id_reason_id_pk" PRIMARY KEY("reason_text_id","reason_id")
);
--> statement-breakpoint
CREATE TABLE "reason_texts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"text_raw" text NOT NULL,
	"text_norm" text NOT NULL,
	"norm_sha256" text NOT NULL,
	"occurrences" integer DEFAULT 0 NOT NULL,
	"legal_refs" text[],
	"covered_char_ratio" numeric(4, 3),
	"rules_version" integer DEFAULT 0 NOT NULL,
	"review_state" "review_state" DEFAULT 'auto' NOT NULL,
	"classified_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "reasons" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"slug" text NOT NULL,
	"normalized_key" text NOT NULL,
	"text_pt" text NOT NULL,
	"text_en" text,
	"text_ru" text,
	"category_id" smallint NOT NULL,
	"status" "reason_status" DEFAULT 'active' NOT NULL,
	"merged_into_id" uuid,
	"source" "reason_source" DEFAULT 'rule' NOT NULL,
	"llm_model" text,
	"prompt_version" text,
	"is_manually_edited" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "source_page_html" (
	"page_id" uuid PRIMARY KEY NOT NULL,
	"html" text NOT NULL,
	"sha256" text NOT NULL,
	"fetched_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "source_page_stats" (
	"page_id" uuid PRIMARY KEY NOT NULL,
	"edition_date" date NOT NULL,
	"acts_total" integer DEFAULT 0 NOT NULL,
	"acts_by_kind" jsonb,
	"approvals" integer DEFAULT 0 NOT NULL,
	"denials_new" integer DEFAULT 0 NOT NULL,
	"denials_upheld" integer DEFAULT 0 NOT NULL,
	"other_decisions" integer DEFAULT 0 NOT NULL,
	"people_total" integer DEFAULT 0 NOT NULL,
	"countries_distinct" integer DEFAULT 0 NOT NULL,
	"states_distinct" integer DEFAULT 0 NOT NULL,
	"reasons_distinct" integer DEFAULT 0 NOT NULL,
	"reason_categories_distinct" integer DEFAULT 0 NOT NULL,
	"top_country_id" smallint,
	"top_reason_category_id" smallint,
	"age_avg" numeric(5, 2),
	"people_without_birth_date" integer DEFAULT 0 NOT NULL,
	"unparsed_paragraphs" integer DEFAULT 0 NOT NULL,
	"people_without_country" integer DEFAULT 0 NOT NULL,
	"reason_texts_uncovered" integer DEFAULT 0 NOT NULL,
	"avg_covered_char_ratio" numeric(4, 3),
	"parser_version" integer DEFAULT 0 NOT NULL,
	"computed_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "source_pages" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"url_title" text NOT NULL,
	"url" text NOT NULL,
	"edition_date" date NOT NULL,
	"section" text DEFAULT 'do1' NOT NULL,
	"edition_number" text,
	"page_number" text,
	"art_type" text,
	"pub_order" integer,
	"hierarchy_str" text,
	"title" text,
	"selected_by" "selected_by" DEFAULT 'hierarchy' NOT NULL,
	"fetch_status" "fetch_status" DEFAULT 'pending' NOT NULL,
	"http_status" integer,
	"fetch_attempts" integer DEFAULT 0 NOT NULL,
	"next_attempt_at" timestamp with time zone,
	"fetch_error" text,
	"fetched_at" timestamp with time zone,
	"html_sha256" text,
	"parser_version" integer DEFAULT 0 NOT NULL,
	"parse_status" "parse_status" DEFAULT 'pending' NOT NULL,
	"parsed_at" timestamp with time zone,
	"parse_error" text
);
--> statement-breakpoint
ALTER TABLE "acts" ADD CONSTRAINT "acts_page_id_source_pages_id_fk" FOREIGN KEY ("page_id") REFERENCES "public"."source_pages"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "approvals" ADD CONSTRAINT "approvals_act_id_acts_id_fk" FOREIGN KEY ("act_id") REFERENCES "public"."acts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "approvals" ADD CONSTRAINT "approvals_page_id_source_pages_id_fk" FOREIGN KEY ("page_id") REFERENCES "public"."source_pages"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "approvals" ADD CONSTRAINT "approvals_country_id_countries_id_fk" FOREIGN KEY ("country_id") REFERENCES "public"."countries"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "approvals" ADD CONSTRAINT "approvals_state_id_br_states_id_fk" FOREIGN KEY ("state_id") REFERENCES "public"."br_states"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "br_state_aliases" ADD CONSTRAINT "br_state_aliases_state_id_br_states_id_fk" FOREIGN KEY ("state_id") REFERENCES "public"."br_states"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "country_aliases" ADD CONSTRAINT "country_aliases_country_id_countries_id_fk" FOREIGN KEY ("country_id") REFERENCES "public"."countries"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "daily_country_stats" ADD CONSTRAINT "daily_country_stats_country_id_countries_id_fk" FOREIGN KEY ("country_id") REFERENCES "public"."countries"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "daily_reason_category_stats" ADD CONSTRAINT "daily_reason_category_stats_category_id_reason_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."reason_categories"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "daily_state_stats" ADD CONSTRAINT "daily_state_stats_state_id_br_states_id_fk" FOREIGN KEY ("state_id") REFERENCES "public"."br_states"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "denial_reasons" ADD CONSTRAINT "denial_reasons_denial_id_denials_id_fk" FOREIGN KEY ("denial_id") REFERENCES "public"."denials"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "denial_reasons" ADD CONSTRAINT "denial_reasons_reason_id_reasons_id_fk" FOREIGN KEY ("reason_id") REFERENCES "public"."reasons"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "denial_reasons" ADD CONSTRAINT "denial_reasons_category_id_reason_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."reason_categories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "denials" ADD CONSTRAINT "denials_act_id_acts_id_fk" FOREIGN KEY ("act_id") REFERENCES "public"."acts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "denials" ADD CONSTRAINT "denials_page_id_source_pages_id_fk" FOREIGN KEY ("page_id") REFERENCES "public"."source_pages"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "denials" ADD CONSTRAINT "denials_reason_text_id_reason_texts_id_fk" FOREIGN KEY ("reason_text_id") REFERENCES "public"."reason_texts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "denials" ADD CONSTRAINT "denials_appeal_of_id_denials_id_fk" FOREIGN KEY ("appeal_of_id") REFERENCES "public"."denials"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reason_text_reasons" ADD CONSTRAINT "reason_text_reasons_reason_text_id_reason_texts_id_fk" FOREIGN KEY ("reason_text_id") REFERENCES "public"."reason_texts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reason_text_reasons" ADD CONSTRAINT "reason_text_reasons_reason_id_reasons_id_fk" FOREIGN KEY ("reason_id") REFERENCES "public"."reasons"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reasons" ADD CONSTRAINT "reasons_category_id_reason_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."reason_categories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reasons" ADD CONSTRAINT "reasons_merged_into_id_reasons_id_fk" FOREIGN KEY ("merged_into_id") REFERENCES "public"."reasons"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "source_page_html" ADD CONSTRAINT "source_page_html_page_id_source_pages_id_fk" FOREIGN KEY ("page_id") REFERENCES "public"."source_pages"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "source_page_stats" ADD CONSTRAINT "source_page_stats_page_id_source_pages_id_fk" FOREIGN KEY ("page_id") REFERENCES "public"."source_pages"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "source_page_stats" ADD CONSTRAINT "source_page_stats_top_country_id_countries_id_fk" FOREIGN KEY ("top_country_id") REFERENCES "public"."countries"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "source_page_stats" ADD CONSTRAINT "source_page_stats_top_reason_category_id_reason_categories_id_fk" FOREIGN KEY ("top_reason_category_id") REFERENCES "public"."reason_categories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "acts_page_ordinal_key" ON "acts" USING btree ("page_id","ordinal");--> statement-breakpoint
CREATE INDEX "acts_kind_edition_date_idx" ON "acts" USING btree ("act_kind","edition_date" DESC NULLS LAST);--> statement-breakpoint
CREATE UNIQUE INDEX "approvals_act_paragraph_key" ON "approvals" USING btree ("act_id","paragraph_sha256");--> statement-breakpoint
CREATE INDEX "approvals_feed_idx" ON "approvals" USING btree ("edition_date" DESC NULLS LAST,"id" DESC NULLS LAST) WHERE "approvals"."retired_at" is null;--> statement-breakpoint
CREATE INDEX "approvals_country_idx" ON "approvals" USING btree ("country_id","edition_date" DESC NULLS LAST,"id" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "approvals_state_idx" ON "approvals" USING btree ("state_id","edition_date" DESC NULLS LAST,"id" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "approvals_page_idx" ON "approvals" USING btree ("page_id");--> statement-breakpoint
CREATE INDEX "approvals_name_trgm_idx" ON "approvals" USING gin ("name_norm" gin_trgm_ops);--> statement-breakpoint
CREATE INDEX "br_state_aliases_state_idx" ON "br_state_aliases" USING btree ("state_id");--> statement-breakpoint
CREATE UNIQUE INDEX "br_states_uf_key" ON "br_states" USING btree ("uf");--> statement-breakpoint
CREATE UNIQUE INDEX "countries_iso2_key" ON "countries" USING btree ("iso2");--> statement-breakpoint
CREATE INDEX "country_aliases_country_idx" ON "country_aliases" USING btree ("country_id");--> statement-breakpoint
CREATE INDEX "daily_country_stats_country_idx" ON "daily_country_stats" USING btree ("country_id","day");--> statement-breakpoint
CREATE INDEX "daily_reason_category_stats_cat_idx" ON "daily_reason_category_stats" USING btree ("category_id","day");--> statement-breakpoint
CREATE INDEX "daily_state_stats_state_idx" ON "daily_state_stats" USING btree ("state_id","day");--> statement-breakpoint
CREATE INDEX "denial_reasons_category_idx" ON "denial_reasons" USING btree ("category_id","edition_date" DESC NULLS LAST,"denial_id");--> statement-breakpoint
CREATE INDEX "denial_reasons_reason_idx" ON "denial_reasons" USING btree ("reason_id","edition_date");--> statement-breakpoint
CREATE UNIQUE INDEX "denials_act_block_key" ON "denials" USING btree ("act_id","block_ordinal");--> statement-breakpoint
CREATE UNIQUE INDEX "denials_codigo_key" ON "denials" USING btree ("codigo") WHERE "denials"."codigo" is not null;--> statement-breakpoint
CREATE INDEX "denials_feed_idx" ON "denials" USING btree ("edition_date" DESC NULLS LAST,"id" DESC NULLS LAST) WHERE "denials"."counts_as_new_denial" and "denials"."retired_at" is null;--> statement-breakpoint
CREATE INDEX "denials_all_feed_idx" ON "denials" USING btree ("edition_date" DESC NULLS LAST,"id" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "denials_process_idx" ON "denials" USING btree ("process_number_norm","edition_date");--> statement-breakpoint
CREATE INDEX "denials_page_idx" ON "denials" USING btree ("page_id");--> statement-breakpoint
CREATE INDEX "denials_reason_text_idx" ON "denials" USING btree ("reason_text_id");--> statement-breakpoint
CREATE INDEX "denials_name_trgm_idx" ON "denials" USING gin ("name_norm" gin_trgm_ops);--> statement-breakpoint
CREATE INDEX "ingest_days_claim_idx" ON "ingest_days" USING btree ("priority","edition_date" DESC NULLS LAST) WHERE "ingest_days"."status" = 'pending';--> statement-breakpoint
CREATE INDEX "ingest_days_status_idx" ON "ingest_days" USING btree ("status");--> statement-breakpoint
CREATE INDEX "job_runs_started_at_idx" ON "job_runs" USING btree ("started_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "job_runs_job_name_started_at_idx" ON "job_runs" USING btree ("job_name","started_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "job_runs_status_idx" ON "job_runs" USING btree ("status");--> statement-breakpoint
CREATE UNIQUE INDEX "reason_categories_code_key" ON "reason_categories" USING btree ("code");--> statement-breakpoint
CREATE INDEX "reason_text_reasons_reason_idx" ON "reason_text_reasons" USING btree ("reason_id");--> statement-breakpoint
CREATE UNIQUE INDEX "reason_texts_norm_key" ON "reason_texts" USING btree ("norm_sha256");--> statement-breakpoint
CREATE INDEX "reason_texts_claim_idx" ON "reason_texts" USING btree ("rules_version") WHERE "reason_texts"."review_state" in ('auto', 'needs_review');--> statement-breakpoint
CREATE INDEX "reason_texts_norm_trgm_idx" ON "reason_texts" USING gin ("text_norm" gin_trgm_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "reasons_slug_key" ON "reasons" USING btree ("slug");--> statement-breakpoint
CREATE UNIQUE INDEX "reasons_normalized_key" ON "reasons" USING btree ("normalized_key");--> statement-breakpoint
CREATE INDEX "reasons_category_idx" ON "reasons" USING btree ("category_id");--> statement-breakpoint
CREATE INDEX "source_page_stats_feed_idx" ON "source_page_stats" USING btree ("edition_date" DESC NULLS LAST,"page_id" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "source_page_stats_people_idx" ON "source_page_stats" USING btree ("people_total" DESC NULLS LAST,"page_id" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "source_page_stats_uncovered_idx" ON "source_page_stats" USING btree ("edition_date" DESC NULLS LAST) WHERE "source_page_stats"."reason_texts_uncovered" > 0;--> statement-breakpoint
CREATE INDEX "source_page_stats_unparsed_idx" ON "source_page_stats" USING btree ("edition_date" DESC NULLS LAST) WHERE "source_page_stats"."unparsed_paragraphs" > 0;--> statement-breakpoint
CREATE UNIQUE INDEX "source_pages_url_title_key" ON "source_pages" USING btree ("url_title");--> statement-breakpoint
CREATE INDEX "source_pages_edition_date_idx" ON "source_pages" USING btree ("edition_date" DESC NULLS LAST,"id" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "source_pages_fetch_claim_idx" ON "source_pages" USING btree ("next_attempt_at") WHERE "source_pages"."fetch_status" in ('pending', 'failed');--> statement-breakpoint
CREATE INDEX "source_pages_parse_claim_idx" ON "source_pages" USING btree ("parser_version") WHERE "source_pages"."fetch_status" = 'fetched';