/**
 * Country reference generator: ISO-3166 plus names in pt/en/ru.
 *
 *   npx tsx scripts/generate-countries.ts
 *
 * The output is committed (`src/db/seeds/countries.generated.ts`), so
 * i18n-iso-countries is only needed by the developer and doesn't end up
 * in the worker image. Rerun when the package updates.
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import countries from 'i18n-iso-countries'
import en from 'i18n-iso-countries/langs/en.json' with { type: 'json' }
import pt from 'i18n-iso-countries/langs/pt.json' with { type: 'json' }
import ru from 'i18n-iso-countries/langs/ru.json' with { type: 'json' }

countries.registerLocale(en)
countries.registerLocale(pt)
countries.registerLocale(ru)

const out = fileURLToPath(new URL('../src/db/seeds/countries.generated.ts', import.meta.url))

type Row = { iso2: string; iso3: string | null; namePt: string; nameEn: string; nameRu: string }

const rows: Row[] = []
const skipped: string[] = []

for (const iso2 of Object.keys(countries.getAlpha2Codes()).sort()) {
  const namePt = countries.getName(iso2, 'pt')
  const nameEn = countries.getName(iso2, 'en')
  const nameRu = countries.getName(iso2, 'ru')

  // Without a Portuguese name the row is useless: matching goes by it.
  if (!namePt || !nameEn) {
    skipped.push(iso2)
    continue
  }

  rows.push({
    iso2,
    iso3: countries.alpha2ToAlpha3(iso2) ?? null,
    namePt,
    nameEn,
    // The Russian name may be missing, so fall back to the English one.
    nameRu: nameRu || nameEn,
  })
}

const body = `/* Generated by scripts/generate-countries.ts. Do not edit by hand. */

export type CountrySeed = {
  iso2: string
  iso3: string | null
  namePt: string
  nameEn: string
  nameRu: string
}

export const COUNTRY_SEED: readonly CountrySeed[] = ${JSON.stringify(rows, null, 2)} as const
`

writeFileSync(out, body, 'utf8')
console.log(`[countries] wrote ${rows.length} countries to ${out}`)
if (skipped.length) console.log(`[countries] skipped for missing name: ${skipped.join(', ')}`)
